### PR TITLE
Add more go versions to build process fixes #82

### LINKED ISSUE #82: Ensure worksheets is go 1.10 compliant
Right now, we test on go 1.8 (see Circle CI config). It would be good to test on multiple versions of go, including 1.10.

### PR DESCRIPTION
**Pull request by cbelsole**
Added more go versions to run in parallel for building.

### CODE REVIEW

**Comment by pascallouisperez** [comment]
Thanks @cbelsole. Is there not a way to share the build steps? I was googling and found this https://discuss.circleci.com/t/build-matrix-configuration/14448 which links to a refactored version. Can we try

```
steps: &steps
      - checkout

      # wait on postgres sql to start
      - run:
          command: while ! nc -z localhost 5432; do echo "postgres not ready"; sleep 0.1; done
          timeout: 5
...
```

and then

```
jobs:
  buildGoXyz:
    docker:
    <<: *steps
    ...
```

**Comment by cbelsole** [comment]
Unfortunately not, due to the checkout step being a string instead of a map [merges at this level do not work](http://yaml-online-parser.appspot.com/?yaml=version%3A+2%0Ajobs%3A%0A++buildGo1.8%3A%0A++++docker%3A%0A++++++-+image%3A+circleci%2Fgolang%3A1.8%0A++++++-+image%3A+circleci%2Fpostgres%3A9.5-alpine%0A++++++++environment%3A%0A++++++++++POSTGRES_USER%3A+ws_user%0A++++++++++POSTGRES_DB%3A+ws_test%0A++++++++++POSTGRES_PASSWORD%3A+%22%22%0A%0A++++working_directory%3A+%2Fgo%2Fsrc%2Fgithub.com%2Fhelloeave%2Fworksheets%0A%0A++++steps%3A+%26steps%0A++++++-+checkout%0A%0A++++++%23+wait+on+postgres+sql+to+start%0A++++++-+run%3A%0A++++++++++command%3A+while+!+nc+-z+localhost+5432%3B+do+echo+%22postgres+not+ready%22%3B+sleep+0.1%3B+done%0A++++++++++timeout%3A+5%0A%0A++++++%23+postgres%0A++++++-+run%3A+sudo+apt+install+postgresql-client%0A++++++-+run%3A+psql+ws_test+ws_user+-h+localhost+-p+5432+-f+%2Fgo%2Fsrc%2Fgithub.com%2Fhelloeave%2Fworksheets%2Fschema.sql%0A%0A++++++%23+golang%0A++++++-+run%3A+go+get+-v+-t+-d+.%2F...%0A++++++-+run%3A+rm+-Rf+%2Fgo%2Fsrc%2Fgithub.com%2Fsatori%2Fgo.uuid%0A++++++-+run%3A+mkdir+%2Fgo%2Fsrc%2Fgithub.com%2Fsatori%2Fgo.uuid%0A++++++-+run%3A+curl+https%3A%2F%2Fraw.githubusercontent.com%2Fsatori%2Fgo.uuid%2Fb061729afc07e77a8aa4fad0a2fd840958f1942a%2Fuuid.go+%3E+%2Fgo%2Fsrc%2Fgithub.com%2Fsatori%2Fgo.uuid%2Fuuid.go%0A++++++-+run%3A+go+test+-v+.%2F...%0A++++++-+run%3A+go+run+tools%2Fwstest.go+%60find+features+-name+%27*.feature%27%60%0A++++++-+run%3A+go+build+-tags%3Dgofuzz+.%2F...%0A%0A++buildGo1.9.4%3A%0A++++docker%3A%0A++++++-+image%3A+circleci%2Fgolang%3A1.9.4%0A++++++-+image%3A+circleci%2Fpostgres%3A9.5-alpine%0A++++++++environment%3A%0A++++++++++POSTGRES_USER%3A+ws_user%0A++++++++++POSTGRES_DB%3A+ws_test%0A++++++++++POSTGRES_PASSWORD%3A+%22%22%0A%0A++++working_directory%3A+%2Fgo%2Fsrc%2Fgithub.com%2Fhelloeave%2Fworksheets%0A%0A++++%3C%3C%3A+*steps%0A%0A++buildGo1.10%3A%0A++++docker%3A%0A++++++-+image%3A+circleci%2Fgolang%3A1.10%0A++++++-+image%3A+circleci%2Fpostgres%3A9.5-alpine%0A++++++++environment%3A%0A++++++++++POSTGRES_USER%3A+ws_user%0A++++++++++POSTGRES_DB%3A+ws_test%0A++++++++++POSTGRES_PASSWORD%3A+%22%22%0A%0A++++working_directory%3A+%2Fgo%2Fsrc%2Fgithub.com%2Fhelloeave%2Fworksheets%0A%0A++++%3C%3C%3A+*steps%0A%0Aworkflows%3A%0A++version%3A+2%0A++build%3A%0A++++jobs%3A%0A++++++-+buildGo1.8%0A++++++-+buildGo1.9.4%0A++++++-+buildGo1.10%0A&type=json).

**Comment by alexandrinaw** [comment]
I think it'll work if we make it more like in the [refactored version](http://yaml-online-parser.appspot.com/?yaml=version%3A+2.0%0A%0Ashared%3A+%26shared%0A++++working_directory%3A+~%2Fcircleci-demo-workflows%0A++++steps%3A%0A++++++-+checkout%0A++++++-+run%3A+bundle+install+--path+vendor%2Fbundle%0A++++++-+run%3A+bundle+exec+rake+db%3Acreate+db%3Aschema%3Aload%0A++++++-+run%3A%0A++++++++++name%3A+Run+tests%0A++++++++++command%3A+rake%0A%0Ajobs%3A%0A++%22ruby-2.2%22%3A++%0A++++%3C%3C%3A+*shared%0A++++docker%3A%0A++++++-+image%3A+circleci%2Fruby%3A2.2-node%0A++++++-) of the link above. I think it needs like one more level of nesting to make it work.

**Comment by alexandrinaw** [comment]
[i think this would work?](http://yaml-online-parser.appspot.com/?yaml=shared%3A+%26shared%0A++steps%3A%0A++++++-+checkout%0A%0A++++++%23+wait+on+postgres+sql+to+start%0A++++++-+run%3A%0A++++++++++command%3A+while+!+nc+-z+localhost+5432%3B+do+echo+%22postgres+not+ready%22%3B+sleep+0.1%3B+done%0A++++++++++timeout%3A+5%0A%0A++++++%23+postgres%0A++++++-+run%3A+sudo+apt+install+postgresql-client%0A++++++-+run%3A+psql+ws_test+ws_user+-h+localhost+-p+5432+-f+%2Fgo%2Fsrc%2Fgithub.com%2Fhelloeave%2Fworksheets%2Fschema.sql%0A%0A++++++%23+golang%0A++++++-+run%3A+go+get+-v+-t+-d+.%2F...%0A++++++-+run%3A+rm+-Rf+%2Fgo%2Fsrc%2Fgithub.com%2Fsatori%2Fgo.uuid%0A++++++-+run%3A+mkdir+%2Fgo%2Fsrc%2Fgithub.com%2Fsatori%2Fgo.uuid%0A++++++-+run%3A+curl+https%3A%2F%2Fraw.githubusercontent.com%2Fsatori%2Fgo.uuid%2Fb061729afc07e77a8aa4fad0a2fd840958f1942a%2Fuuid.go+%3E+%2Fgo%2Fsrc%2Fgithub.com%2Fsatori%2Fgo.uuid%2Fuuid.go%0A++++++-+run%3A+go+test+-v+.%2F...%0A++++++-+run%3A+go+run+tools%2Fwstest.go+%60find+features+-name+%27*.feature%27%60%0A++++++-+run%3A+go+build+-tags%3Dgofuzz+.%2F...%0A%0Aversion%3A+2%0Ajobs%3A%0A++buildGo1.8%3A%0A++++docker%3A%0A++++++-+image%3A+circleci%2Fgolang%3A1.8%0A++++++-+image%3A+circleci%2Fpostgres%3A9.5-alpine%0A++++++++environment%3A%0A++++++++++POSTGRES_USER%3A+ws_user%0A++++++++++POSTGRES_DB%3A+ws_test%0A++++++++++POSTGRES_PASSWORD%3A+%22%22%0A%0A++++working_directory%3A+%2Fgo%2Fsrc%2Fgithub.com%2Fhelloeave%2Fworksheets%0A%0A++++%3C%3C%3A+*shared%0A%0A++buildGo1.9.4%3A%0A++++docker%3A%0A++++++-+image%3A+circleci%2Fgolang%3A1.9.4%0A++++++-+image%3A+circleci%2Fpostgres%3A9.5-alpine%0A++++++++environment%3A%0A++++++++++POSTGRES_USER%3A+ws_user%0A++++++++++POSTGRES_DB%3A+ws_test%0A++++++++++POSTGRES_PASSWORD%3A+%22%22%0A%0A++++working_directory%3A+%2Fgo%2Fsrc%2Fgithub.com%2Fhelloeave%2Fworksheets%0A%0A++++%3C%3C%3A+*shared%0A%0A++buildGo1.10%3A%0A++++docker%3A%0A++++++-+image%3A+circleci%2Fgolang%3A1.10%0A++++++-+image%3A+circleci%2Fpostgres%3A9.5-alpine%0A++++++++environment%3A%0A++++++++++POSTGRES_USER%3A+ws_user%0A++++++++++POSTGRES_DB%3A+ws_test%0A++++++++++POSTGRES_PASSWORD%3A+%22%22%0A%0A++++working_directory%3A+%2Fgo%2Fsrc%2Fgithub.com%2Fhelloeave%2Fworksheets%0A%0A++++%3C%3C%3A+*shared%0A%0Aworkflows%3A%0A++version%3A+2%0A++build%3A%0A++++jobs%3A%0A++++++-+buildGo1.8%0A++++++-+buildGo1.9.4%0A++++++-+buildGo1.10%0A&type=json)

**Comment by cbelsole** [comment]
@alexandrinaw That worked.

**Pull request merged**
